context:
  version: "2.11.1"

package:
  name: eon
  version: ${{ version }}

source:
  - url: https://github.com/TheochemUI/eOn/releases/download/v${{ version }}/eon-v${{ version }}.tar.xz
    sha256: 6bf6d52e0f726408828fc9bbe327ff33d71781b8d2d5e414f74d148929615485
  - url: https://github.com/OmniPotentRPC/rgpot/archive/refs/tags/v1.0.2.tar.gz
    sha256: db0e204d139f4713784a554fa9b0c3aab87c9f17907c6caed1b4b8874f50dfaf
    target_directory: subprojects/rgpot

build:
  number: 0
requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - if: not win
      then: ${{ compiler('fortran') }}
    - cmake
    - ninja
    - meson
    - pkg-config
    - sccache
    - if: (build_platform != target_platform)
      then:
        - python
        - cross-python_${{ target_platform }}
    - capnproto
    - if: osx
      then: llvm-openmp
  host:
    - python
    - pip
    - numpy
    - pyyaml
    - setuptools
    # build against CPU, CUDA at runtime
    # with linker trick
    - libtorch *cpu*
    - libtorch
    - libmetatomic-torch >=0.1.7,<0.2
    - libmetatensor
    - libmetatensor-torch >=0.8,<0.9
    - xtb
    - eigen >=3.4,<3.5
    - if: win
      then:
        - libblas * *mkl
        - libcblas * *mkl
        - liblapack * *mkl
        - liblapacke * *mkl
    - if: not win
      then:
        - libblas
        - libcblas
        - liblapack
        - liblapacke
    - fmt
    - spdlog
    - capnproto
    - if: osx
      then: llvm-openmp
  run:
    - python
    - pyyaml
    - numpy
    - xtb
    - fmt
    - spdlog
    - capnproto
    - libmetatomic-torch >=0.1.7,<0.2
    - libmetatensor-torch
    - if: osx
      then: llvm-openmp

tests:
  - if: (build_platform == target_platform)
    then:
      script:
        - python -c "import eon"
      requirements:
        run:
          - libtorch *cpu*
  - if: (build_platform == target_platform)
    then:
      script:
        - eonclient -h
        - eonclient --version
      requirements:
        run:
          - libtorch *cpu*


about:
  homepage: https://eondocs.org/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "Algorithms for long time scales and potential energy surface exploration"
  description: |
    The EON software package contains algorithms used primarily to model the
    evolution of atomic scale systems over long time scales. This version is
    instrumented for working with Metatensor.
  documentation: https://eondocs.org/index.html
  repository: https://github.com/TheochemUI/eOn

extra:
  recipe-maintainers:
    - HaoZeke
