context:
  version: "2.8.1"

package:
  name: eon
  version: ${{ version }}

source:
  url: https://github.com/TheochemUI/eOn/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 6c81d1666b9aeb5e1db8efe57e5d5f4c05f46f03eeb003eed70344d250b58e00

build:
  number: 0
  skip:
    - win
requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - cmake
    - ninja
    - meson
    - sccache
    - if: (build_platform != target_platform)
      then:
        - python
        - cross-python_${{ target_platform }}
    - if: osx
      then: llvm-openmp
  host:
    - python
    - pip
    - numpy
    - pyyaml
    - setuptools
    - libtorch >=2.8,<2.9 *cpu*
    - libmetatomic-torch >=0.1,<0.2
    - libmetatensor-torch >=0.8,<0.9
    - eigen >=3.4,<3.5
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - fmt
    - spdlog
    - if: osx
      then: llvm-openmp
  run:
    - python
    - pyyaml
    - numpy
    - eigen
    - fmt
    - spdlog
    - libmetatomic-torch >=0.1,<0.2
    - libmetatensor-torch
    - if: osx
      then: llvm-openmp

tests:
  - python:
      imports:
        - eon.server
  - script:
      - eonclient -h

about:
  homepage: https://eondocs.org/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "Algorithms for long time scales and potential energy surface exploration"
  description: |
    The EON software package contains algorithms used primarily to model the
    evolution of atomic scale systems over long time scales. This version is
    instrumented for working with Metatensor.
  documentation: https://eondocs.org/index.html
  repository: https://github.com/TheochemUI/eOn

extra:
  recipe-maintainers:
    - HaoZeke
