context:
  version: "2.10.0"

package:
  name: eon
  version: ${{ version }}

source:
  url: https://github.com/TheochemUI/eOn/releases/download/v${{ version }}/eOn-${{ version }}.tar.gz
  sha256: 7d07eb7edfbd5bfb37d929b2ce91ce4592b254171479dab5278843ee97852cb9

build:
  number: 0
  skip:
    - win
requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - cmake
    - ninja
    - meson
    - sccache
    - if: (build_platform != target_platform)
      then:
        - python
        - cross-python_${{ target_platform }}
    - if: osx
      then: llvm-openmp
  host:
    - python
    - pip
    - numpy
    - pyyaml
    - setuptools
    # build against CPU, CUDA at runtime
    # with linker trick
    - libtorch *cpu*
    - libtorch
    - libmetatomic-torch >=0.1.7,<0.2
    - libmetatensor-torch >=0.8,<0.9
    - xtb
    - eigen >=3.4,<3.5
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - fmt
    - spdlog
    - if: osx
      then: llvm-openmp
  run:
    - python
    - pyyaml
    - numpy
    - xtb
    - fmt
    - spdlog
    - libmetatomic-torch >=0.1.7,<0.2
    - libmetatensor-torch
    - if: osx
      then: llvm-openmp

tests:
  - script:
      - python -c "import eon; print(eon.__version__)"
      - python -c "import eon.server"
      - python -c "from eon.schema import MainConfig; print(list(MainConfig.model_fields.keys()))"
      - python -c "from eon.config import config"
    requirements:
      run:
        - libtorch *cpu*
        - pydantic
  - script:
      - eonclient -h
      - eonclient --version
    requirements:
      run:
        - libtorch *cpu*


about:
  homepage: https://eondocs.org/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "Algorithms for long time scales and potential energy surface exploration"
  description: |
    The EON software package contains algorithms used primarily to model the
    evolution of atomic scale systems over long time scales. This version is
    instrumented for working with Metatensor.
  documentation: https://eondocs.org/index.html
  repository: https://github.com/TheochemUI/eOn

extra:
  recipe-maintainers:
    - HaoZeke
