context:
  version: "2.9.0"

package:
  name: eon
  version: ${{ version }}

source:
  url: https://github.com/TheochemUI/eOn/releases/download/v${{ version }}/eon-v${{ version }}.tar.xz
  sha256: dcaa7af1a020c3968bad022ac38b265a0410b4b1183c7058400cf6c29e67394e

build:
  number: 0
  skip:
    - win
requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - cmake
    - ninja
    - meson
    - sccache
    - if: (build_platform != target_platform)
      then:
        - python
        - cross-python_${{ target_platform }}
    - if: osx
      then: llvm-openmp
  host:
    - python
    - pip
    - numpy
    - pyyaml
    - setuptools
    - libtorch >=2.9,<2.10 *cpu*
    - libmetatomic-torch >=0.1.7,<0.2
    - libmetatensor-torch >=0.8,<0.9
    - eigen >=3.4,<3.5
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - fmt >=12
    - spdlog >=1.16
    - if: osx
      then: llvm-openmp
  run:
    - python
    - pyyaml
    - numpy
    - eigen
    - fmt
    - spdlog
    - libmetatomic-torch >=0.1.7,<0.2
    - libmetatensor-torch
    - if: osx
      then: llvm-openmp

tests:
  - script:
      - python -c "import eon.server"
    requirements:
      run:
        - libtorch *cpu*
  - script:
      - eonclient -h
    requirements:
      run:
        - libtorch *cpu*


about:
  homepage: https://eondocs.org/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "Algorithms for long time scales and potential energy surface exploration"
  description: |
    The EON software package contains algorithms used primarily to model the
    evolution of atomic scale systems over long time scales. This version is
    instrumented for working with Metatensor.
  documentation: https://eondocs.org/index.html
  repository: https://github.com/TheochemUI/eOn

extra:
  recipe-maintainers:
    - HaoZeke
