context:
  version: "2.10.1"

package:
  name: eon
  version: ${{ version }}

source:
  url: https://github.com/TheochemUI/eOn/releases/download/v${{ version }}/eon-v${{ version }}.tar.xz
  sha256: dcaa7af1a020c3968bad022ac38b265a0410b4b1183c7058400cf6c29e67394e
  patches:
    - fix-datetime-utc-py310.patch
    - fix-fortran-xtb-decouple.patch
    - fix-vla-msvc.patch

build:
  number: 1
requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - if: not win
      then: ${{ compiler('fortran') }}
    - cmake
    - ninja
    - meson
    - pkg-config
    - sccache
    - if: (build_platform != target_platform)
      then:
        - python
        - cross-python_${{ target_platform }}
    - if: osx
      then: llvm-openmp
  host:
    - python
    - pip
    - numpy
    - pyyaml
    - setuptools
    # build against CPU, CUDA at runtime
    # with linker trick
    - libtorch *cpu*
    - libtorch
    - libmetatomic-torch >=0.1.7,<0.2
    - libmetatensor-torch >=0.8,<0.9
    - xtb
    - eigen >=3.4,<3.5
    - if: win
      then:
        - libblas * *mkl
        - libcblas * *mkl
        - liblapack * *mkl
        - liblapacke * *mkl
    - if: not win
      then:
        - libblas
        - libcblas
        - liblapack
        - liblapacke
    - fmt
    - spdlog
    - if: osx
      then: llvm-openmp
  run:
    - python
    - pyyaml
    - numpy
    - xtb
    - fmt
    - spdlog
    - libmetatomic-torch >=0.1.7,<0.2
    - libmetatensor-torch
    - if: osx
      then: llvm-openmp

tests:
  - if: (build_platform == target_platform)
    then:
      script:
        - python -c "import eon"
      requirements:
        run:
          - libtorch *cpu*
  - if: (build_platform == target_platform)
    then:
      script:
        - eonclient -h
        - eonclient --version
      requirements:
        run:
          - libtorch *cpu*


about:
  homepage: https://eondocs.org/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "Algorithms for long time scales and potential energy surface exploration"
  description: |
    The EON software package contains algorithms used primarily to model the
    evolution of atomic scale systems over long time scales. This version is
    instrumented for working with Metatensor.
  documentation: https://eondocs.org/index.html
  repository: https://github.com/TheochemUI/eOn

extra:
  recipe-maintainers:
    - HaoZeke
